trigger:
- main

pool:
  # name: 'Default'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
 - stage: Build
   displayName: Build and Unit Testing  
   jobs:
   - job: "Build"
     steps:
     - task: NuGetToolInstaller@1
   
     - task: NuGetCommand@2
       inputs:
         restoreSolution: '$(solution)'

     - task: DotNetCoreCLI@2
       displayName: 'dotnet build $(buildConfiguration)'
       inputs:
         command: 'build'
         arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

     - task: DotNetCoreCLI@2
       displayName: 'dotnet run unit testing'
       inputs:
         command: 'test'
         arguments: '--configuration $(buildConfiguration) --output $(Common.TestResultsDirectory)'

 - stage: DeployOnHml
   displayName: Deploy on hml
   jobs:
   - deployment:
     displayName: "Tasks to deploy"
     environment: "Approvers"
     pool: 
        vmImage: 'windows-latest'
        # name: 'Default'
     continueOnError: 'false'
     strategy:
       runOnce:
         deploy:      
           steps:
           - task: FtpUpload@2
             displayName: Send FTP
             inputs:
               credentialsOption: 'inputs'
               serverUrl: 'ftp://arielgiacomini-003@WIN8130.SITE4NOW.NET'
               username: 'finance-organization-hml'
               password: 'finance-organization-hml'
               rootDirectory: '$(Build.ArtifactStagingDirectory)'
               filePatterns: '*
                             !*.json'
               remoteDirectory: '/api.finance.hml'
               #remoteDirectory: '/teste'
               enableUtf8: true
               clean: false
               cleanContents: false
               preservePaths: false
               trustSSL: false