trigger:
- main

pool:
  name: 'Default'
  # vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
 - stage: Build
   displayName: Build and Unit Testing  
   jobs:
   - job: "Build"
     steps:
     - task: NuGetToolInstaller@1
   
     - task: NuGetCommand@2
       inputs:
         restoreSolution: '$(solution)'

     - task: DotNetCoreCLI@2
       displayName: 'dotnet build $(buildConfiguration)'
       inputs:
         command: 'build'
         arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'FinanceOrganization.WebApi'
         publishLocation: 'Container'

     - task: DotNetCoreCLI@2
       displayName: 'dotnet run unit testing'
       inputs:
         command: 'test'
         arguments: '--configuration $(buildConfiguration) --output $(Common.TestResultsDirectory)'

 - stage: DeployOnHml
   displayName: Deploy on hml
   jobs:
   - deployment:
     displayName: "Tasks to deploy on hml"
     environment: "Approvers HML"
     pool: 
        # vmImage: 'windows-latest'
        name: 'Default'
     continueOnError: 'false'
     strategy:
       runOnce:
         deploy:      
           steps:
           - task: FtpUpload@2
             displayName: Send FTP
             inputs:
               credentialsOption: 'inputs'
               serverUrl: 'ftp://arielgiacomini-003@WIN8130.SITE4NOW.NET'
               username: 'finance-organization-hml'
               password: 'finance-organization-hml'
               rootDirectory: '$(Pipeline.Workspace)/FinanceOrganization.WebApi'
               filePatterns: "**"
               remoteDirectory: '/api.finance.hml'
               enableUtf8: true

 - stage: DeployOnPrd
   displayName: Deploy on prd
   jobs:
   - deployment:
     displayName: "Tasks to deploy on prd"
     environment: "Approvers PRD"
     pool: 
        vmImage: 'windows-latest'
        # name: 'Default'
     continueOnError: 'false'
     strategy:
       runOnce:
         deploy:      
           steps:
           - task: FtpUpload@2
             displayName: Send FTP
             inputs:
               credentialsOption: 'inputs'
               serverUrl: 'ftp://arielgiacomini-003@WIN8130.SITE4NOW.NET'
               username: 'finance-organization-prd'
               password: 'finance-organization-prd'
               rootDirectory: '$(Build.ArtifactStagingDirectory)'
               filePatterns: '**'
               remoteDirectory: '/api.finance.prd'
               enableUtf8: true