trigger:
- main

pool:
  # name: 'Default'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'FinanceOrganization.WebApi'
  websiteName: 'api.finance.hml'
  appPoolName: 'arielgiacomini-003'

stages:
 - stage: Build
   displayName: Build and Unit Testing  
   jobs:
   - job: "Build"
     steps:
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: 'restore'
            projects: '*.sln'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '*.sln'
            arguments: --configuration Release

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '*.sln'
            arguments: '--configuration $(BuildConfiguration)'
       
        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true

        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop

 - stage: RunTests
   displayName: Run tests
   jobs:
   - job: "Build"
     steps:
     - task: DotNetCoreCLI@2
       displayName: 'dotnet run unit testing'
       inputs:
         command: 'test'
         arguments: '--configuration $(buildConfiguration) --output $(Common.TestResultsDirectory)'

 - stage: DeployOnHml
   displayName: Deploy on hml
   jobs:
   - deployment:
     displayName: "Tasks to deploy on hml"
     environment: "Approvers HML"
     pool: 
        vmImage: 'windows-latest'
        # name: 'Default'
     continueOnError: 'false'
     variables:
     - name: websitePhysicalPath
       value: '%SystemDrive%\inetpub\wwwroot\$(websiteName)'
     strategy:
       runOnce:
         deploy:      
           steps:
           - task: IISWebAppManagementOnMachineGroup@0
             inputs:            
               IISDeploymentType: 'IISWebsite'
               ActionIISWebsite: 'CreateOrUpdateWebsite'
               WebsiteName: '$(websiteName)'
               WebsitePhysicalPath: '$(websitePhysicalPath)'
               WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
               CreateOrUpdateAppPoolForWebsite: true
               AppPoolNameForWebsite: '$(appPoolName)'
               DotNetVersionForWebsite: 'No Managed Code'
               PipeLineModeForWebsite: 'Integrated'
               AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
               AddBinding: true
               Bindings: |
                   {
                       bindings:[
                           {
                               "protocol":"http",
                               "ipAddress":"",
                               "hostname":"",
                               "port":"80",
                               "sslThumbprint":"",
                               "sniFlag":false
                           }
                       ]
                   }
           
           - task: IISWebAppDeploymentOnMachineGroup@0
             inputs:
               WebSiteName: '$(websiteName)'
               Package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/$(projectName).zip'

 # - stage: DeployOnPrd
 #   displayName: Deploy on prd
 #   jobs:
 #   - deployment:
 #     displayName: "Tasks to deploy on prd"
 #     environment: "Approvers PRD"
 #     pool: 
 #        vmImage: 'windows-latest'
 #        # name: 'Default'
 #     continueOnError: 'false'
 #     strategy:
 #       runOnce:
 #         deploy:      
 #           steps:
           # - task: FtpUpload@2
           #   displayName: Send FTP
           #   inputs:
           #     credentialsOption: 'inputs'
           #     serverUrl: 'ftp://finance-organization-hml@WIN8130.SITE4NOW.NET'
           #     username: 'finance-organization-hml'
           #     password: 'finance-organization-hml'
           #     rootDirectory: '$(Pipeline.Workspace)/FinanceOrganization.WebApi'
           #     filePatterns: "**"
           #     remoteDirectory: '/'
           #     enableUtf8: true